# Generated by Django 6.0.1 on 2026-01-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'Fijo / Indeterminado'), ('temporary', 'Contratado / Determinado'), ('intern', 'Pasante')], default='permanent', max_length=20, verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hcm_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro Póliza HCM'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='food_stamps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cesta Ticket'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='rrhh.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='period_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='period_year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vacation', 'Vacaciones'), ('medical', 'Reposo Médico'), ('personal', 'Permiso Personal'), ('bereavement', 'Duelo')], max_length=20)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='rrhh.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('laptop', 'Computadora'), ('phone', 'Teléfono Celular'), ('tool', 'Herramienta'), ('uniform', 'Uniforme'), ('id_card', 'Carnet')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='rrhh.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('spouse', 'Esposo/a'), ('child', 'Hijo/a'), ('parent', 'Padre/Madre')], max_length=20)),
                ('birth_date', models.DateField()),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='rrhh.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='observations',
        ),
    ]
