# Generated by Django 6.0.1 on 2026-01-24 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_employee_system_user_historicalemployee_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Presidente'), (1, 'Vice Presidente'), (2, 'Gerente General'), (3, 'Gerente'), (4, 'Coordinador'), (5, 'Especialista / Operativo')], default=5, verbose_name='Nivel Jerárquico'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='rrhh.employee', verbose_name='Supervisor Directo'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Presidente'), (1, 'Vice Presidente'), (2, 'Gerente General'), (3, 'Gerente'), (4, 'Coordinador'), (5, 'Especialista / Operativo')], default=5, verbose_name='Nivel Jerárquico'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.employee', verbose_name='Supervisor Directo'),
        ),
    ]
