# Generated by Django 6.0.1 on 2026-01-24 23:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_alter_employee_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHRRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('vacation', 'Vacaciones'), ('benefits', 'Prestaciones Sociales'), ('certificate', 'Constancia de Trabajo'), ('loan', 'Préstamo/Adelanto'), ('other', 'Otras Solicitudes')], max_length=20, verbose_name='Tipo de Trámite')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reason', models.TextField(verbose_name='Justificación / Detalle')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio (Si aplica)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin (Si aplica)')),
                ('supervisor_comment', models.TextField(blank=True, verbose_name='Comentarios del Supervisor')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.employee', verbose_name='Solicitante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Solicitud de RRHH',
                'verbose_name_plural': 'historical Solicitudes de RRHH',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vacation', 'Vacaciones'), ('benefits', 'Prestaciones Sociales'), ('certificate', 'Constancia de Trabajo'), ('loan', 'Préstamo/Adelanto'), ('other', 'Otras Solicitudes')], max_length=20, verbose_name='Tipo de Trámite')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reason', models.TextField(verbose_name='Justificación / Detalle')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio (Si aplica)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin (Si aplica)')),
                ('supervisor_comment', models.TextField(blank=True, verbose_name='Comentarios del Supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_requests', to='rrhh.employee', verbose_name='Solicitante')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de RRHH',
                'verbose_name_plural': 'Solicitudes de RRHH',
                'ordering': ['-created_at'],
            },
        ),
    ]
