# Generated by Django 6.0.1 on 2026-01-24 23:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_historicalhrrequest_hrrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerformanceEvaluation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('period_month', models.IntegerField(verbose_name='Mes')),
                ('period_year', models.IntegerField(verbose_name='Año')),
                ('score', models.IntegerField(verbose_name='Calificación (1-100)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios de Desempeño')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.employee', verbose_name='Empleado')),
                ('evaluated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Evaluación de Desempeño',
                'verbose_name_plural': 'historical Evaluaciones de Desempeño',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.IntegerField(verbose_name='Mes')),
                ('period_year', models.IntegerField(verbose_name='Año')),
                ('score', models.IntegerField(verbose_name='Calificación (1-100)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios de Desempeño')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rrhh.employee', verbose_name='Empleado')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de Desempeño',
                'verbose_name_plural': 'Evaluaciones de Desempeño',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('employee', 'period_month', 'period_year')},
            },
        ),
    ]
