# Generated by Django 6.0.1 on 2026-01-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_historicalperformanceevaluation_bonus_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipo / Activo', 'verbose_name_plural': 'Equipos e Inventario'},
        ),
        migrations.AlterModelOptions(
            name='historicalequipment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Equipo / Activo', 'verbose_name_plural': 'historical Equipos e Inventario'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='internal_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Activo/Inventario'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('functional', 'En Uso / Funcional'), ('failing', 'Presenta Fallas'), ('broken', 'Dañado / No Funciona'), ('maintenance', 'En Mantenimiento'), ('replaced', 'Sustituido / Retirado')], default='functional', max_length=20, verbose_name='Estado de Operatividad'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='internal_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código de Activo/Inventario'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='status',
            field=models.CharField(choices=[('functional', 'En Uso / Funcional'), ('failing', 'Presenta Fallas'), ('broken', 'Dañado / No Funciona'), ('maintenance', 'En Mantenimiento'), ('replaced', 'Sustituido / Retirado')], default='functional', max_length=20, verbose_name='Estado de Operatividad'),
        ),
        migrations.AddField(
            model_name='historicalhrrequest',
            name='equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.equipment', verbose_name='Equipo Involucrado'),
        ),
        migrations.AddField(
            model_name='hrrequest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_requests', to='rrhh.equipment', verbose_name='Equipo Involucrado'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('laptop', 'Computadora'), ('phone', 'Teléfono Celular'), ('tool', 'Herramienta'), ('uniform', 'Uniforme'), ('id_card', 'Carnet'), ('furniture', 'Mueble de Oficina')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='rrhh.employee', verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Devuelto'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie S/N'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='assigned_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='category',
            field=models.CharField(choices=[('laptop', 'Computadora'), ('phone', 'Teléfono Celular'), ('tool', 'Herramienta'), ('uniform', 'Uniforme'), ('id_card', 'Carnet'), ('furniture', 'Mueble de Oficina')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.employee', verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Devuelto'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie S/N'),
        ),
        migrations.AlterField(
            model_name='historicalhrrequest',
            name='type',
            field=models.CharField(choices=[('vacation', 'Vacaciones'), ('benefits', 'Prestaciones Sociales'), ('certificate', 'Constancia de Trabajo'), ('loan', 'Préstamo/Adelanto'), ('equip_fault', 'Reporte de Falla de Equipo'), ('other', 'Otras Solicitudes')], max_length=20, verbose_name='Tipo de Trámite'),
        ),
        migrations.AlterField(
            model_name='hrrequest',
            name='type',
            field=models.CharField(choices=[('vacation', 'Vacaciones'), ('benefits', 'Prestaciones Sociales'), ('certificate', 'Constancia de Trabajo'), ('loan', 'Préstamo/Adelanto'), ('equip_fault', 'Reporte de Falla de Equipo'), ('other', 'Otras Solicitudes')], max_length=20, verbose_name='Tipo de Trámite'),
        ),
    ]
