# Generated by Django 6.0.1 on 2026-01-25 00:33

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_alter_equipment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaintenanceLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Servicio')),
                ('type', models.CharField(choices=[('preventive', 'Preventivo / Rutina'), ('corrective', 'Correctivo / Reparación'), ('upgrade', 'Mejora / Upgrade')], default='corrective', max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('description', models.TextField(verbose_name='Detalle del Trabajo')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo del Servicio ($)')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Técnico / Empresa Responsable')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rrhh.equipment', verbose_name='Equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Log de Mantenimiento',
                'verbose_name_plural': 'historical Logs de Mantenimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Servicio')),
                ('type', models.CharField(choices=[('preventive', 'Preventivo / Rutina'), ('corrective', 'Correctivo / Reparación'), ('upgrade', 'Mejora / Upgrade')], default='corrective', max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('description', models.TextField(verbose_name='Detalle del Trabajo')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo del Servicio ($)')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Técnico / Empresa Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='rrhh.equipment', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Log de Mantenimiento',
                'verbose_name_plural': 'Logs de Mantenimientos',
                'ordering': ['-date'],
            },
        ),
    ]
