# Generated by Django 6.0.1 on 2026-01-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_historicalmaintenancelog_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blacklist_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Desincorporación'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='blacklist_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Desincorporación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('vacation', 'En Vacaciones'), ('on_leave', 'Permiso/Reposo'), ('retired', 'Retirado'), ('blacklisted', 'Lista Negra / Egresado')], default='active', max_length=20, verbose_name='Estado Laboral'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('vacation', 'En Vacaciones'), ('on_leave', 'Permiso/Reposo'), ('retired', 'Retirado'), ('blacklisted', 'Lista Negra / Egresado')], default='active', max_length=20, verbose_name='Estado Laboral'),
        ),
    ]
