# Generated by Django 6.0.1 on 2026-01-25 01:22

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilometraje Actual')),
                ('status', models.CharField(choices=[('operative', 'Operativo'), ('maintenance', 'En Taller'), ('broken', 'Fuera de Servicio'), ('leased', 'Alquilado / Tercero')], default='operative', max_length=20)),
                ('insurance_policy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cód. Póliza')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento Seguro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=20, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilometraje Actual')),
                ('status', models.CharField(choices=[('operative', 'Operativo'), ('maintenance', 'En Taller'), ('broken', 'Fuera de Servicio'), ('leased', 'Alquilado / Tercero')], default='operative', max_length=20)),
                ('insurance_policy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cód. Póliza')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento Seguro')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vehículo',
                'verbose_name_plural': 'historical Vehículos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVehicleMaintenance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('preventive', 'Preventivo (Aceite/Cauchos)'), ('corrective', 'Correctivo / Reparación'), ('inspection', 'Inspección Rutinaria')], default='preventive', max_length=20)),
                ('description', models.TextField(verbose_name='Descripción del Trabajo')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performed_by', models.CharField(max_length=100, verbose_name='Taller / Responsable')),
                ('next_due_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Próximo a (Km)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistica.vehicle')),
            ],
            options={
                'verbose_name': 'historical Mantenimiento Vehicular',
                'verbose_name_plural': 'historical Mantenimientos Vehiculares',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFuelLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total ($)')),
                ('odometer_reading', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lectura Odómetro')),
                ('station', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estación de Servicio')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistica.vehicle')),
            ],
            options={
                'verbose_name': 'historical Registro de Combustible',
                'verbose_name_plural': 'historical Registros de Combustible',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total ($)')),
                ('odometer_reading', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lectura Odómetro')),
                ('station', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estación de Servicio')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='logistica.vehicle')),
            ],
            options={
                'verbose_name': 'Registro de Combustible',
                'verbose_name_plural': 'Registros de Combustible',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('preventive', 'Preventivo (Aceite/Cauchos)'), ('corrective', 'Correctivo / Reparación'), ('inspection', 'Inspección Rutinaria')], default='preventive', max_length=20)),
                ('description', models.TextField(verbose_name='Descripción del Trabajo')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performed_by', models.CharField(max_length=100, verbose_name='Taller / Responsable')),
                ('next_due_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Próximo a (Km)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='logistica.vehicle')),
            ],
            options={
                'verbose_name': 'Mantenimiento Vehicular',
                'verbose_name_plural': 'Mantenimientos Vehiculares',
                'ordering': ['-date'],
            },
        ),
    ]
