# Generated by Django 6.0.1 on 2026-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número Telefónico')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción / Alias')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Física')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Número Telefónico',
                'verbose_name_plural': 'Números Telefónicos',
            },
        ),
    ]
