# Generated by Django 6.0.1 on 2026-01-24 22:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_radiobase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Repuesto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario (USD)')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('minimum_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Almacén')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Repuesto',
                'verbose_name_plural': 'Categorías de Repuestos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción / Justificación')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Solicitado')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Aprobado')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('executed', 'Ejecutado')], default='draft', max_length=20, verbose_name='Estado')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de Aprobación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBudget',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción / Justificación')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Solicitado')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Aprobado')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('executed', 'Ejecutado')], default='draft', max_length=20, verbose_name='Estado')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de Aprobación')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'historical Presupuesto',
                'verbose_name_plural': 'historical Presupuestos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.budget', verbose_name='Presupuesto')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='inventory.sparepart', verbose_name='Repuesto')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto',
                'verbose_name_plural': 'Ítems de Presupuesto',
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='inventory.sparepartcategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='HistoricalSparePart',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Repuesto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario (USD)')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('minimum_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Almacén')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.sparepartcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'historical Repuesto',
                'verbose_name_plural': 'historical Repuestos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(verbose_name='Cantidad Usada')),
                ('unit_price_at_usage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario al Momento del Uso')),
                ('incident_type', models.CharField(choices=[('phone', 'Teléfono'), ('radiobase', 'Radiobase')], max_length=20, verbose_name='Tipo de Incidencia')),
                ('incident_id', models.IntegerField(verbose_name='ID de Incidencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.sparepart', verbose_name='Repuesto')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_usages', to=settings.AUTH_USER_MODEL, verbose_name='Usado por')),
            ],
            options={
                'verbose_name': 'Uso de Repuesto',
                'verbose_name_plural': 'Usos de Repuestos',
                'ordering': ['-used_at'],
            },
        ),
    ]
