/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/audit/': RouteRecordInfo<'/audit/', '/audit', Record<never, never>, Record<never, never>>,
    '/budgets/': RouteRecordInfo<'/budgets/', '/budgets', Record<never, never>, Record<never, never>>,
    '/budgets/[id]': RouteRecordInfo<'/budgets/[id]', '/budgets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/employees/': RouteRecordInfo<'/employees/', '/employees', Record<never, never>, Record<never, never>>,
    '/employees/[id]': RouteRecordInfo<'/employees/[id]', '/employees/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/employees/create': RouteRecordInfo<'/employees/create', '/employees/create', Record<never, never>, Record<never, never>>,
    '/failure-types/': RouteRecordInfo<'/failure-types/', '/failure-types', Record<never, never>, Record<never, never>>,
    '/failure-types/[id]': RouteRecordInfo<'/failure-types/[id]', '/failure-types/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/failure-types/create': RouteRecordInfo<'/failure-types/create', '/failure-types/create', Record<never, never>, Record<never, never>>,
    '/incidents/': RouteRecordInfo<'/incidents/', '/incidents', Record<never, never>, Record<never, never>>,
    '/incidents/[id]': RouteRecordInfo<'/incidents/[id]', '/incidents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/incidents/create': RouteRecordInfo<'/incidents/create', '/incidents/create', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/payroll/': RouteRecordInfo<'/payroll/', '/payroll', Record<never, never>, Record<never, never>>,
    '/phones/': RouteRecordInfo<'/phones/', '/phones', Record<never, never>, Record<never, never>>,
    '/phones/[id]': RouteRecordInfo<'/phones/[id]', '/phones/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/phones/create': RouteRecordInfo<'/phones/create', '/phones/create', Record<never, never>, Record<never, never>>,
    '/radio-bases/': RouteRecordInfo<'/radio-bases/', '/radio-bases', Record<never, never>, Record<never, never>>,
    '/radio-bases/[id]': RouteRecordInfo<'/radio-bases/[id]', '/radio-bases/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/radio-bases/create': RouteRecordInfo<'/radio-bases/create', '/radio-bases/create', Record<never, never>, Record<never, never>>,
    '/rb-incidents/': RouteRecordInfo<'/rb-incidents/', '/rb-incidents', Record<never, never>, Record<never, never>>,
    '/rb-incidents/[id]': RouteRecordInfo<'/rb-incidents/[id]', '/rb-incidents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/rb-incidents/create': RouteRecordInfo<'/rb-incidents/create', '/rb-incidents/create', Record<never, never>, Record<never, never>>,
    '/spare-parts/': RouteRecordInfo<'/spare-parts/', '/spare-parts', Record<never, never>, Record<never, never>>,
    '/spare-parts/[id]': RouteRecordInfo<'/spare-parts/[id]', '/spare-parts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]': RouteRecordInfo<'/users/[id]', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/create': RouteRecordInfo<'/users/create', '/users/create', Record<never, never>, Record<never, never>>,
    '/users/me': RouteRecordInfo<'/users/me', '/users/me', Record<never, never>, Record<never, never>>,
    '/work-orders/': RouteRecordInfo<'/work-orders/', '/work-orders', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/audit/index.vue': {
      routes: '/audit/'
      views: never
    }
    'src/pages/budgets/index.vue': {
      routes: '/budgets/'
      views: never
    }
    'src/pages/budgets/[id].vue': {
      routes: '/budgets/[id]'
      views: never
    }
    'src/pages/employees/index.vue': {
      routes: '/employees/'
      views: never
    }
    'src/pages/employees/[id].vue': {
      routes: '/employees/[id]'
      views: never
    }
    'src/pages/employees/create.vue': {
      routes: '/employees/create'
      views: never
    }
    'src/pages/failure-types/index.vue': {
      routes: '/failure-types/'
      views: never
    }
    'src/pages/failure-types/[id].vue': {
      routes: '/failure-types/[id]'
      views: never
    }
    'src/pages/failure-types/create.vue': {
      routes: '/failure-types/create'
      views: never
    }
    'src/pages/incidents/index.vue': {
      routes: '/incidents/'
      views: never
    }
    'src/pages/incidents/[id].vue': {
      routes: '/incidents/[id]'
      views: never
    }
    'src/pages/incidents/create.vue': {
      routes: '/incidents/create'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/payroll/index.vue': {
      routes: '/payroll/'
      views: never
    }
    'src/pages/phones/index.vue': {
      routes: '/phones/'
      views: never
    }
    'src/pages/phones/[id].vue': {
      routes: '/phones/[id]'
      views: never
    }
    'src/pages/phones/create.vue': {
      routes: '/phones/create'
      views: never
    }
    'src/pages/radio-bases/index.vue': {
      routes: '/radio-bases/'
      views: never
    }
    'src/pages/radio-bases/[id].vue': {
      routes: '/radio-bases/[id]'
      views: never
    }
    'src/pages/radio-bases/create.vue': {
      routes: '/radio-bases/create'
      views: never
    }
    'src/pages/rb-incidents/index.vue': {
      routes: '/rb-incidents/'
      views: never
    }
    'src/pages/rb-incidents/[id].vue': {
      routes: '/rb-incidents/[id]'
      views: never
    }
    'src/pages/rb-incidents/create.vue': {
      routes: '/rb-incidents/create'
      views: never
    }
    'src/pages/spare-parts/index.vue': {
      routes: '/spare-parts/'
      views: never
    }
    'src/pages/spare-parts/[id].vue': {
      routes: '/spare-parts/[id]'
      views: never
    }
    'src/pages/users/index.vue': {
      routes: '/users/'
      views: never
    }
    'src/pages/users/[id].vue': {
      routes: '/users/[id]'
      views: never
    }
    'src/pages/users/create.vue': {
      routes: '/users/create'
      views: never
    }
    'src/pages/users/me.vue': {
      routes: '/users/me'
      views: never
    }
    'src/pages/work-orders/index.vue': {
      routes: '/work-orders/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
