/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analytics/performance': RouteRecordInfo<'/analytics/performance', '/analytics/performance', Record<never, never>, Record<never, never>>,
    '/approvals/': RouteRecordInfo<'/approvals/', '/approvals', Record<never, never>, Record<never, never>>,
    '/audit/': RouteRecordInfo<'/audit/', '/audit', Record<never, never>, Record<never, never>>,
    '/auditor/': RouteRecordInfo<'/auditor/', '/auditor', Record<never, never>, Record<never, never>>,
    '/budgets/': RouteRecordInfo<'/budgets/', '/budgets', Record<never, never>, Record<never, never>>,
    '/budgets/[id]': RouteRecordInfo<'/budgets/[id]', '/budgets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/departments/': RouteRecordInfo<'/departments/', '/departments', Record<never, never>, Record<never, never>>,
    '/departments/org-chart': RouteRecordInfo<'/departments/org-chart', '/departments/org-chart', Record<never, never>, Record<never, never>>,
    '/documentos/': RouteRecordInfo<'/documentos/', '/documentos', Record<never, never>, Record<never, never>>,
    '/employees/': RouteRecordInfo<'/employees/', '/employees', Record<never, never>, Record<never, never>>,
    '/employees/[id]': RouteRecordInfo<'/employees/[id]', '/employees/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/failure-types/': RouteRecordInfo<'/failure-types/', '/failure-types', Record<never, never>, Record<never, never>>,
    '/failure-types/[id]': RouteRecordInfo<'/failure-types/[id]', '/failure-types/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/help/manual': RouteRecordInfo<'/help/manual', '/help/manual', Record<never, never>, Record<never, never>>,
    '/incidents/': RouteRecordInfo<'/incidents/', '/incidents', Record<never, never>, Record<never, never>>,
    '/incidents/[id]': RouteRecordInfo<'/incidents/[id]', '/incidents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/inventory/assets': RouteRecordInfo<'/inventory/assets', '/inventory/assets', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logistica/fleet': RouteRecordInfo<'/logistica/fleet', '/logistica/fleet', Record<never, never>, Record<never, never>>,
    '/payroll/': RouteRecordInfo<'/payroll/', '/payroll', Record<never, never>, Record<never, never>>,
    '/phones/': RouteRecordInfo<'/phones/', '/phones', Record<never, never>, Record<never, never>>,
    '/phones/[id]': RouteRecordInfo<'/phones/[id]', '/phones/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/procura/suppliers': RouteRecordInfo<'/procura/suppliers', '/procura/suppliers', Record<never, never>, Record<never, never>>,
    '/radio-bases/': RouteRecordInfo<'/radio-bases/', '/radio-bases', Record<never, never>, Record<never, never>>,
    '/radio-bases/[id]': RouteRecordInfo<'/radio-bases/[id]', '/radio-bases/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/rb-incidents/': RouteRecordInfo<'/rb-incidents/', '/rb-incidents', Record<never, never>, Record<never, never>>,
    '/rb-incidents/[id]': RouteRecordInfo<'/rb-incidents/[id]', '/rb-incidents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/rrhh/blacklist': RouteRecordInfo<'/rrhh/blacklist', '/rrhh/blacklist', Record<never, never>, Record<never, never>>,
    '/self-service/': RouteRecordInfo<'/self-service/', '/self-service', Record<never, never>, Record<never, never>>,
    '/spare-parts/': RouteRecordInfo<'/spare-parts/', '/spare-parts', Record<never, never>, Record<never, never>>,
    '/spare-parts/[id]': RouteRecordInfo<'/spare-parts/[id]', '/spare-parts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]': RouteRecordInfo<'/users/[id]', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/me': RouteRecordInfo<'/users/me', '/users/me', Record<never, never>, Record<never, never>>,
    '/ventas/': RouteRecordInfo<'/ventas/', '/ventas', Record<never, never>, Record<never, never>>,
    '/wiki/': RouteRecordInfo<'/wiki/', '/wiki', Record<never, never>, Record<never, never>>,
    '/work-orders/': RouteRecordInfo<'/work-orders/', '/work-orders', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/analytics/performance.vue': {
      routes: '/analytics/performance'
      views: never
    }
    'src/pages/approvals/index.vue': {
      routes: '/approvals/'
      views: never
    }
    'src/pages/audit/index.vue': {
      routes: '/audit/'
      views: never
    }
    'src/pages/auditor/index.vue': {
      routes: '/auditor/'
      views: never
    }
    'src/pages/budgets/index.vue': {
      routes: '/budgets/'
      views: never
    }
    'src/pages/budgets/[id].vue': {
      routes: '/budgets/[id]'
      views: never
    }
    'src/pages/departments/index.vue': {
      routes: '/departments/'
      views: never
    }
    'src/pages/departments/org-chart.vue': {
      routes: '/departments/org-chart'
      views: never
    }
    'src/pages/documentos/index.vue': {
      routes: '/documentos/'
      views: never
    }
    'src/pages/employees/index.vue': {
      routes: '/employees/'
      views: never
    }
    'src/pages/employees/[id].vue': {
      routes: '/employees/[id]'
      views: never
    }
    'src/pages/failure-types/index.vue': {
      routes: '/failure-types/'
      views: never
    }
    'src/pages/failure-types/[id].vue': {
      routes: '/failure-types/[id]'
      views: never
    }
    'src/pages/help/manual.vue': {
      routes: '/help/manual'
      views: never
    }
    'src/pages/incidents/index.vue': {
      routes: '/incidents/'
      views: never
    }
    'src/pages/incidents/[id].vue': {
      routes: '/incidents/[id]'
      views: never
    }
    'src/pages/inventory/assets.vue': {
      routes: '/inventory/assets'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/logistica/fleet.vue': {
      routes: '/logistica/fleet'
      views: never
    }
    'src/pages/payroll/index.vue': {
      routes: '/payroll/'
      views: never
    }
    'src/pages/phones/index.vue': {
      routes: '/phones/'
      views: never
    }
    'src/pages/phones/[id].vue': {
      routes: '/phones/[id]'
      views: never
    }
    'src/pages/procura/suppliers.vue': {
      routes: '/procura/suppliers'
      views: never
    }
    'src/pages/radio-bases/index.vue': {
      routes: '/radio-bases/'
      views: never
    }
    'src/pages/radio-bases/[id].vue': {
      routes: '/radio-bases/[id]'
      views: never
    }
    'src/pages/rb-incidents/index.vue': {
      routes: '/rb-incidents/'
      views: never
    }
    'src/pages/rb-incidents/[id].vue': {
      routes: '/rb-incidents/[id]'
      views: never
    }
    'src/pages/rrhh/blacklist.vue': {
      routes: '/rrhh/blacklist'
      views: never
    }
    'src/pages/self-service/index.vue': {
      routes: '/self-service/'
      views: never
    }
    'src/pages/spare-parts/index.vue': {
      routes: '/spare-parts/'
      views: never
    }
    'src/pages/spare-parts/[id].vue': {
      routes: '/spare-parts/[id]'
      views: never
    }
    'src/pages/users/index.vue': {
      routes: '/users/'
      views: never
    }
    'src/pages/users/[id].vue': {
      routes: '/users/[id]'
      views: never
    }
    'src/pages/users/me.vue': {
      routes: '/users/me'
      views: never
    }
    'src/pages/ventas/index.vue': {
      routes: '/ventas/'
      views: never
    }
    'src/pages/wiki/index.vue': {
      routes: '/wiki/'
      views: never
    }
    'src/pages/work-orders/index.vue': {
      routes: '/work-orders/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
