# Generated by Django 6.0.1 on 2026-01-25 02:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_sparepart_sparepartcategory_budget_historicalbudget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('dni', models.CharField(max_length=30, unique=True, verbose_name='Cédula / RIF / Pasaporte')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('address', models.TextField(verbose_name='Dirección de Domicilio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('dni', models.CharField(db_index=True, max_length=30, verbose_name='Cédula / RIF / Pasaporte')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('address', models.TextField(verbose_name='Dirección de Domicilio')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSimCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('iccid', models.CharField(db_index=True, max_length=20, verbose_name='ICCID')),
                ('type', models.CharField(choices=[('physical', 'SIM Física'), ('esim', 'eSIM (Virtual)')], default='physical', max_length=20, verbose_name='Tipo de SIM')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendida'), ('defective', 'Defectuosa')], default='available', max_length=20, verbose_name='Estado')),
                ('puk', models.CharField(max_length=20, verbose_name='PUK')),
                ('pin', models.CharField(max_length=10, verbose_name='PIN')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.phonenumber', verbose_name='Número Asignado')),
            ],
            options={
                'verbose_name': 'historical SIM Card',
                'verbose_name_plural': 'historical SIM Cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20, unique=True, verbose_name='ICCID')),
                ('type', models.CharField(choices=[('physical', 'SIM Física'), ('esim', 'eSIM (Virtual)')], default='physical', max_length=20, verbose_name='Tipo de SIM')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendida'), ('defective', 'Defectuosa')], default='available', max_length=20, verbose_name='Estado')),
                ('puk', models.CharField(max_length=20, verbose_name='PUK')),
                ('pin', models.CharField(max_length=10, verbose_name='PIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_card', to='inventory.phonenumber', verbose_name='Número Asignado')),
            ],
            options={
                'verbose_name': 'SIM Card',
                'verbose_name_plural': 'SIM Cards',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Venta (USD)')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta (Punto de Venta)'), ('transfer', 'Transferencia / Pago Móvil'), ('zelle', 'Zelle')], max_length=20, verbose_name='Método de Pago')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/sales/', verbose_name='Contrato Digital')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='ventas.customer', verbose_name='Cliente')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('sim_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='ventas.simcard', verbose_name='SIM Card Vendida')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Venta (USD)')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta (Punto de Venta)'), ('transfer', 'Transferencia / Pago Móvil'), ('zelle', 'Zelle')], max_length=20, verbose_name='Método de Pago')),
                ('sale_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Venta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('contract_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Contrato Digital')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.customer', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('sim_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.simcard', verbose_name='SIM Card Vendida')),
            ],
            options={
                'verbose_name': 'historical Venta',
                'verbose_name_plural': 'historical Ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
