# Generated by Django 6.0.1 on 2026-01-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsimcard',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendida'), ('defective', 'Defectuosa'), ('deactivated', 'Desactivada / Migrada')], default='available', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendida'), ('defective', 'Defectuosa'), ('deactivated', 'Desactivada / Migrada')], default='available', max_length=20, verbose_name='Estado'),
        ),
    ]
