# Generated by Django 6.0.1 on 2026-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Falla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Detalle de la Incidencia')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio de Falla')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('solved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Solucionada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En Revisión'), ('solved', 'Solucionada'), ('postponed', 'Pospuesta')], default='pending', max_length=20, verbose_name='Estado')),
                ('solution_comment', models.TextField(blank=True, verbose_name='Comentarios de Solución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
