# Generated by Django 6.0.1 on 2026-01-24 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='incident',
            name='failure_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.failuretype', verbose_name='Tipo de Falla'),
        ),
        migrations.AddField(
            model_name='incident',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='inventory.phonenumber', verbose_name='Número Afectado'),
        ),
    ]
