# Generated by Django 6.0.1 on 2026-01-24 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_initial'),
        ('inventory', '0002_radiobase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioBaseIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Detalle de la Incidencia')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio de Falla')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('solved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Solucionada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En Revisión'), ('solved', 'Solucionada'), ('postponed', 'Pospuesta')], default='pending', max_length=20, verbose_name='Estado')),
                ('solution_comment', models.TextField(blank=True, verbose_name='Comentarios de Solución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rb_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rb_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('failure_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidencias.failuretype', verbose_name='Tipo de Falla')),
                ('radio_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='inventory.radiobase', verbose_name='Radiobase Afectada')),
            ],
            options={
                'verbose_name': 'Incidencia de Radiobase',
                'verbose_name_plural': 'Incidencias de Radiobases',
                'ordering': ['-created_at'],
            },
        ),
    ]
