# Generated by Django 6.0.1 on 2026-01-24 20:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_radiobaseincident'),
        ('inventory', '0002_radiobase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Detalle de la Incidencia')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio de Falla')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('solved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Solucionada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En Revisión'), ('solved', 'Solucionada'), ('postponed', 'Pospuesta')], default='pending', max_length=20, verbose_name='Estado')),
                ('solution_comment', models.TextField(blank=True, verbose_name='Comentarios de Solución')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('failure_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidencias.failuretype', verbose_name='Tipo de Falla')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.phonenumber', verbose_name='Número Afectado')),
            ],
            options={
                'verbose_name': 'historical Incidencia',
                'verbose_name_plural': 'historical Incidencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRadioBaseIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Detalle de la Incidencia')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio de Falla')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('solved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Solucionada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En Revisión'), ('solved', 'Solucionada'), ('postponed', 'Pospuesta')], default='pending', max_length=20, verbose_name='Estado')),
                ('solution_comment', models.TextField(blank=True, verbose_name='Comentarios de Solución')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('failure_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidencias.failuretype', verbose_name='Tipo de Falla')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('radio_base', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.radiobase', verbose_name='Radiobase Afectada')),
            ],
            options={
                'verbose_name': 'historical Incidencia de Radiobase',
                'verbose_name_plural': 'historical Incidencias de Radiobases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
