# Generated by Django 6.0.1 on 2026-01-24 20:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('phone', 'Teléfono'), ('radiobase', 'Radiobase')], max_length=20)),
                ('incident_id', models.IntegerField()),
                ('status', models.CharField(choices=[('assigned', 'Asignada'), ('in_progress', 'En Proceso'), ('testing', 'En Pruebas'), ('completed', 'Completada')], default='assigned', max_length=20)),
                ('checked_power', models.BooleanField(default=False)),
                ('checked_wiring', models.BooleanField(default=False)),
                ('checked_config', models.BooleanField(default=False)),
                ('photo_before', models.TextField(blank=True, max_length=100, null=True)),
                ('photo_after', models.TextField(blank=True, max_length=100, null=True)),
                ('technician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Orden de Trabajo',
                'verbose_name_plural': 'historical Órdenes de Trabajo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('phone', 'Teléfono'), ('radiobase', 'Radiobase')], max_length=20)),
                ('incident_id', models.IntegerField()),
                ('status', models.CharField(choices=[('assigned', 'Asignada'), ('in_progress', 'En Proceso'), ('testing', 'En Pruebas'), ('completed', 'Completada')], default='assigned', max_length=20)),
                ('checked_power', models.BooleanField(default=False)),
                ('checked_wiring', models.BooleanField(default=False)),
                ('checked_config', models.BooleanField(default=False)),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='work_orders/')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='work_orders/')),
                ('technician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
            },
        ),
    ]
