# Generated by Django 6.0.1 on 2026-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0006_historicalworkorder_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AddField(
            model_name='historicalradiobaseincident',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AddField(
            model_name='radiobaseincident',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
    ]
