# Generated by Django 6.0.1 on 2026-01-25 00:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0007_historicalincident_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncidentAudit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('support_score', models.IntegerField(verbose_name='Calificación Soporte (1-100)')),
                ('technician_score', models.IntegerField(verbose_name='Calificación Técnico (1-100)')),
                ('comments', models.TextField(blank=True, verbose_name='Observaciones de Auditoría')),
                ('assignment_time_seconds', models.IntegerField(blank=True, null=True)),
                ('resolution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('evaluator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidencias.incident', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'historical Auditoría de Incidencia',
                'verbose_name_plural': 'historical Auditorías de Incidencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IncidentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_score', models.IntegerField(verbose_name='Calificación Soporte (1-100)')),
                ('technician_score', models.IntegerField(verbose_name='Calificación Técnico (1-100)')),
                ('comments', models.TextField(blank=True, verbose_name='Observaciones de Auditoría')),
                ('assignment_time_seconds', models.IntegerField(blank=True, null=True)),
                ('resolution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_performed', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='incidencias.incident', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'Auditoría de Incidencia',
                'verbose_name_plural': 'Auditorías de Incidencias',
            },
        ),
    ]
