# Generated by Django 6.0.1 on 2026-01-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0008_historicalincidentaudit_incidentaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincidentaudit',
            name='bonus_approved',
            field=models.BooleanField(default=False, verbose_name='Bono Aprobado'),
        ),
        migrations.AddField(
            model_name='historicalincidentaudit',
            name='suggested_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bono Sugerido ($)'),
        ),
        migrations.AddField(
            model_name='incidentaudit',
            name='bonus_approved',
            field=models.BooleanField(default=False, verbose_name='Bono Aprobado'),
        ),
        migrations.AddField(
            model_name='incidentaudit',
            name='suggested_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bono Sugerido ($)'),
        ),
    ]
